version: '3.1'

volumes:
  colintmet-mongo-db:
    external: True
  sqlite-django:
    external: True
networks:                                                                       
  colintmet-net:
    external:
      name: colintmet-net
  default:
    driver: bridge

services:

  django-rest-api:
    build: .
    networks:                                                                   
      - colintmet-net
    ports:
      - 8000:8000
    volumes:
      - sqlite-django:/app/

  mongo:
    image: mongo
    restart: always
    networks:
      - colintmet-net
    volumes:
      - colintmet-mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - colintmet-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


