version: '3.1'

volumes:
  colintmet-mongo-db:
    external: True
  sqlite-django:
    external: True
networks:
  colintmet-net:
    external:
      name: colintmet-net
  default:
    driver: bridge

services:

  django-rest-api:
    build: .
    networks:
      - colintmet-net
    ports:
      - 8000:8000
    volumes:
      - sqlite-django:/app/sqlite

  mongo:
    image: mongo
    container_name: some-mongo
    restart: always
    networks:
      - colintmet-net
    volumes:
      - colintmet-mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"

  mongo-express:
    image: mongo-express
    restart: always
    networks:
      - colintmet-net
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME:  "${MONGO_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_ROOT_PASSWORD}"
      ME_CONFIG_BASICAUTH_USERNAME: "${EXPRESS_USER_NAME}"
      ME_CONFIG_BASICAUTH_PASSWORD: "${EXPRESS_PASSWORD}"
