
version: '3.1'

volumes:
  sqlite-django:
    external: True
networks:                                                                       
  colintmet-net:
    external:
      name: colintmet-net
  default:
    driver: bridge

services:

  django-rest-api:
    build: .
    networks:                                                                   
      - colintmet-net
    ports:
      - 8000:8000
    volumes:
      - sqlite-django:/app/

